apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-docker-for-matteolibe-provakubernates-deployment
  labels:
    app: k8s-docker-for-matteolibe-provakubernates
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-docker-for-matteolibe-provakubernates
  template:
    metadata:
      labels:
        app: k8s-docker-for-matteolibe-provakubernates
    spec:
      containers:
      - name: k8s-docker-for-matteolibe-provakubernates
        image: matteolibe/provakubernates-1.0:1.7
        ports:
        - containerPort: 8080